name: ci1_workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check_1_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep 180

      - name: Lint
        run: echo "Lint done."

  check_2_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: check_1_job

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep 180

      - name: Lint
        run: echo "Lint done (2)."
