name: on-all-job-finished

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed
  # check_run:
  #   types: [completed]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: test
        with:
          script: |
            // ref: https://github.com/actions/github-script#run-a-separate-file
            const script = require('./.github/workflows/script.cjs')
            await script({ github, context })
            return 'tmp'
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
